# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('components', models.TextField()),
                ('added_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
