# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_mainproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='seller',
            field=models.CharField(default='', max_length=200),
        ),
    ]
