# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_mainproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='components',
            field=models.CharField(max_length=2000),
        ),
    ]
