# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 11:02
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('webapp', '0004_auto_20171002_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='components',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
