# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20171002_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='tags',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='components',
            field=models.TextField(default=''),
        ),
    ]
