# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='impurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('Cas', models.IntegerField()),
                ('grade', models.CharField(choices=[('IP', 'IP'), ('EP', 'EP'), ('USP', 'USP')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('added_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
