# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20171109_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpurityAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('phone_no', models.IntegerField(default=0)),
                ('impurity_name', models.CharField(default='', max_length=100)),
                ('Cas', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('phone_no', models.IntegerField(default=0)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('Cas', models.IntegerField(default=0)),
                ('grade', models.CharField(default='', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
